version: "3"
services:
  redis:
    container_name: redis-db
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
  userapi:
    container_name: nodejs-userapi
    build: ./userApi
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
