# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Do not pay attention to this parameter
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :virtualbox do |vb|
      config.vbguest.auto_update = false
    end
  end

  # Define the gitlab_server VM
  config.vm.define "devops" do |server|
    # Specify the Vagrant box to use
    server.vm.box = "almalinux/9"
    # Specify the VM ip address
    config.vm.network "forwarded_port", guest: 3000, host: 3000, auto_correct: true
    # Specify the VM specs when using the Virtualbox provisioner
    server.vm.provider "virtualbox" do |vb|
      vb.name =  "devops"
      # VM RAM in MB
      vb.memory = 6134
      # VM CPUs
      vb.cpus = 4
    end
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "6134"
      vmware.vmx["numvcpus"] = "4"
    end
  end

# if this task is taking too much time, make sure that node_modules is not present in ../userApi
config.vm.provision "file", source: "../userApi", destination:"/home/vagrant"

  # Use Vagrant Ansible provisioner
  config.vm.provision "ansible_local" do |ansible|
    # The path to the playbooks entry point
    ansible.playbook = "playbooks/run.yml"
    # Only run the roles with these tags
    ansible.tags = "install", "integrity"
  end
  config.vm.provision "shell", inline: "/vagrant/launcher.sh", run:"always"
end